const CONFIG={whatsapp:'573001234567',email:'info@fpmenajeria.com'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const toast=$('#toast');
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),3200)}
function wa(message){window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(message)}`,'_blank','noopener');}
$$('[data-whatsapp="true"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();wa('Hola, quiero solicitar un envío con FP Mensajería.');}));
const phoneLinks=$$('[data-phone-link]'); phoneLinks.forEach(a=>{a.href=`https://wa.me/${CONFIG.whatsapp}`;a.target='_blank';a.rel='noopener'});
$('#trackingForm').addEventListener('submit',e=>{e.preventDefault();const code=$('#trackingCode').value.trim().toUpperCase();if(!code)return;const known={'FP-2026-001':'En camino · Recogido y en ruta hacia el destino.','FP-2026-002':'Entregado · El envío fue entregado correctamente.','FP-2026-003':'En recolección · Un mensajero se dirige al punto de recogida.'};const status=known[code]||'Guía registrada · Consulta de demostración. Para seguimiento real, conecta este formulario con tu sistema de rastreo/API.';const r=$('#trackingResult');r.textContent=`${code}: ${status}`;r.style.display='block';});
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=`Hola, soy ${f.get('name')}. Mi teléfono es ${f.get('phone')}. Necesito: ${f.get('message')}`;wa(msg);showToast('Abriendo WhatsApp para enviar la solicitud…');e.currentTarget.reset();});
const toggle=$('.menu-toggle'),nav=$('.nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});$$('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const top=$('#toTop');window.addEventListener('scroll',()=>{top.style.display=scrollY>600?'grid':'none'});top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
$('#year').textContent=new Date().getFullYear();
const obs=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting)x.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el));
const counters=$$('[data-counter]');let counted=false;const counterObs=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting)||counted)return;counted=true;counters.forEach(el=>{const target=Number(el.dataset.counter),prefix=el.dataset.prefix||'',suffix=el.dataset.suffix||'';let n=0;const step=Math.max(1,Math.ceil(target/55));const timer=setInterval(()=>{n=Math.min(target,n+step);el.textContent=prefix+n.toLocaleString('es-CO')+suffix;if(n>=target)clearInterval(timer)},22)})},{threshold:.4});counterObs.observe($('.stats'));
